package de.marcus_deuss.inventorytracker.db.entity;

public class Brand {
    // private variables
    private long id;                       // database internal number, must be long!
    private String brandName;

    // Empty constructor
    public Brand(){

    }

    // constructor
    public Brand(long id, String brandName){
        this.id = id;                           // id autogenerated in database
        this.brandName = brandName;
    }

    // getter methods
    public long getId() {
        return id;
    }

    public String getBrandName() {
        return brandName;
    }

    // setter methods

    public void setId(long id) {
        this.id = id;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    @Override
    public String toString() {
        return "id:" + id + ", name:" + brandName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Brand other = (Brand) obj;
        if (id != other.id)
            return false;
        return true;
    }
}
