package de.marcus_deuss.inventorytracker.db.entity;

public class Category {


    // private variables
    private long id;                       // database internal number, must be long!
    private String categoryName;

    // constructor
    public Category(long id, String categoryName){
        this.id = id;                           // id autogenerated in database
        this.categoryName = categoryName;
    }

    // getter methods
    public long getId() {
        return id;
    }

    public String getCategoryName() {
        return categoryName;
    }

    // setter methods

    public void setId(long id) {
        this.id = id;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @Override
    public String toString() {
        return "id:" + id + ", name:" + categoryName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Category other = (Category) obj;
        if (id != other.id)
            return false;
        return true;
    }
}
