package de.marcus_deuss.inventorytracker.db.entity;

public class Category {
    // table name
    public static final String TABLE_NAME = "category";


    // Table Column names
    public static final String COLUMN_ID = "_id";    // should always be id, needed by some android classes
    public static final String COLUMN_CATEGORYNAME = "categoryname";

    // Create table SQL query string
    public static final String CREATE_TABLE = "CREATE TABLE " + TABLE_NAME + "("
            + COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT," + COLUMN_CATEGORYNAME + " TEXT" + ")";

    // private variables
    private long id;                       // database internal number, must be long!
    private String categoryName;

    // constructor
    public Category(long id, String categoryName){
        this.id = id;                           // id autogenerated in database
        this.categoryName = categoryName;
    }

    // getter methods
    public long getId() {
        return id;
    }

    public String getCategoryName() {
        return categoryName;
    }

    // setter methods

    public void setId(long id) {
        this.id = id;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}
