package de.marcus_deuss.inventorytracker.db.entity;


/*
 * Created by marcus on 22.03.18.
 */


// contains inventory of a typical household
public class Inventory {

    // private variables
    private long id;                       // database internal number, must be long!
    private String inventoryName;        // name of inventory
    private String dateOfPurchase;
    private int price;
    private byte[] invoice;               // PDF of already scanned invoice or new invoice rendered vom Jpeg to PDF
    private String timeStamp;              // create date of database entry
    private int warranty;                // warranty in number of months (6,12,18,24,36)
    private String serialNumber;
    private byte[] image;                // link to object image
    private String remark;               // addl. info
    private String ownerName;           // who owns this object in household
    private String brandName;            // (Apple, Sony, Samsung, IKEA etc.)

    // foreign key references
    private long categoryId;            // extra table for holding category names - to support multi language support etc.
    private long roomId;

    // Empty constructor
    public Inventory(){

    }

    // constructor
    public Inventory(long id, String inventoryName, String dateOfPurchase,
                     int price, byte[] invoice, String timeStamp, int warranty,
                     String serialNumber, byte[] image, String remark,
                     String ownerName, String brandName,
                     long roomId, long categoryId){
        this.id = id;                           // id autogenerated in database
        this.inventoryName = inventoryName;
        this.dateOfPurchase = dateOfPurchase;
        this.price = price;
        this.invoice = invoice;
        this.timeStamp = timeStamp;             // will be autogenerated in database
        this.warranty = warranty;
        this.serialNumber = serialNumber;
        this.image = image;
        this.remark = remark;
        this.ownerName = ownerName;
        this.brandName = brandName;
        this.roomId = roomId;
        this.categoryId = categoryId;           // reference to table category
    }


    // getter methods
    public long getId() {
        return id;
    }

    public String getInventoryName() {
        return inventoryName;
    }

    public String getDateOfPurchase() {
        return dateOfPurchase;
    }

    public int getPrice() {
        return price;
    }

    public byte[] getInvoice() {
        return invoice;
    }

    // TODO bug!!!
    public String getTimeStamp() {
        return timeStamp;
    }

    public int getWarranty() {
        return warranty;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public byte[] getImage(){
        return image;
    }

    public String getRemark() {
        return remark;
    }

    public String getOwnerName() {
        return ownerName;
    }

    public long getRoomId() {
        return roomId;
    }

    /* public String getCategoryName() {
        return categoryName;
    } */

    public String getBrandName() {
        return brandName;
    }

    public long getCategoryId() {
        return categoryId;
    }

    // setter methods

    public void setId(long id) {
        this.id = id;
    }

    public void setInventoryName(String inventoryName) {
        this.inventoryName = inventoryName;
    }

    public void setDateOfPurchase(String dateOfPurchase) {
        this.dateOfPurchase = dateOfPurchase;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public void setInvoice(byte[] invoice) {
        this.invoice = invoice;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    public void setWarranty(int warranty) {
        this.warranty = warranty;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public void setImage(byte[] image){
        this.image = image;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }


    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }


    @Override
    public String toString() {
        return "id:" + id + ", name:" + inventoryName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Inventory other = (Inventory) obj;
        if (id != other.id)
            return false;
        return true;
    }
}






