package de.marcus_deuss.inventorytracker.db.entity;

public class Room {
    // private variables
    private long id;                       // database internal number, must be long!
    private String roomName;

    // Empty constructor
    public Room(){

    }

    // constructor
    public Room(long id, String roomName){
        this.id = id;                           // id autogenerated in database
        this.roomName = roomName;
    }

    // getter methods
    public long getId() {
        return id;
    }

    public String getRoomName() {
        return roomName;
    }

    // setter methods

    public void setId(long id) {
        this.id = id;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    @Override
    public String toString() {
        return "id:" + id + ", name:" + roomName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Room other = (Room) obj;
        if (id != other.id)
            return false;
        return true;
    }
}
